// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    NotFound: typeof import('./src/components/NotFound.vue')['default']
    SAFooter: typeof import('./src/components/SAFooter.vue')['default']
    SAHeader: typeof import('./src/components/SAHeader.vue')['default']
    SASection: typeof import('./src/components/SASection.vue')['default']
    SASidebar: typeof import('./src/components/SASidebar.vue')['default']
    SATopbar: typeof import('./src/components/SATopbar.vue')['default']
  }
}

export { }
